.\" Manpage for pvimport.
.\" Contact contact@nslab.at.
.TH man 8 "25.01.2018" "1.3.2" "pvimport man page"
.SH NAME
pvimport \- short script description
.SH SYNOPSIS
pvimport <option|long-option>
.SH DESCRIPTION
pvimport short long description.
.SH OPTIONS
--help
        show this message

--debug
        displays information on the screen (debug mode)

--verbose
        displays 'info' messages on the screen (verbose mode)

--time
        displays execution time, occurs only with --verbose

-c, --config <file>
        attach an external config file to the script
.SH SEE ALSO
https://github.com/trimstray/pvimport
.SH BUGS
No known bugs.
.SH AUTHOR
trimstray (contact@nslab.at)
