#!/usr/bin/env bash

################################################################################
######################## Definitions of user variables #########################
################################################################################


################################################################################
######################## Definitions of user functions #########################
################################################################################

# ``````````````````````````````````````````````````````````````````````````````
# Function name: XenInit()
#
# Description:
#   Initialization of tasks for Xen.
#
# Usage:
#   XenInit
#
# Examples:
#   XenInit
#

function XenInit() {

  local _FUNCTION_ID="XenInit"
  local _STATE=0

  _sprintf "head" "flush configuration of remote environment"

  _logger "head" \
    "${_FUNCTION_ID}()" \
    "flush configuration of remote environment"

  # shellcheck disable=SC2154
  _init_function "FlushRemoteFiles ${_pv_xen_vars}"

  _sprintf "head" "check configuration of remote environment"

  _logger "head" \
    "${_FUNCTION_ID}()" \
    "check configuration of remote environment"

  # shellcheck disable=SC2154
  _init_function "CheckRemoteStorage ${hv_storage}"
  # shellcheck disable=SC2154
  _init_function "XenVmCheck ${vm_id}"

  _sprintf "head" "init configuration of remote environment"

  _logger "head" \
    "${_FUNCTION_ID}()" \
    "init configuration of remote environment"

  re_path="${hv_storage}/${vm_id}"

  _sprintf "info" "set re_path: ${re_path}"

  _logger "head" \
    "${_FUNCTION_ID}()" \
    "set re_path: ${re_path}"

  # shellcheck disable=SC2154
  _init_function "CreateRemoteStorage ${re_path}"

  _sprintf "head" "dump configuration of remote environment"

  _logger "head" \
    "${_FUNCTION_ID}()" \
    "dump configuration of remote environment"

  # shellcheck disable=SC2154
  _init_function "GetRemoteFiles ${_pv_xen_vars} ${_pv_xen_vars}"

  _sprintf "head" "export virtual machine"

  _logger "head" \
    "${_FUNCTION_ID}()" \
    "export virtual machine"

  # shellcheck disable=SC2154
  _init_function "CheckRemoteStorage ${re_path}"

  # shellcheck disable=SC2154
  _init_function "XenVmExport ${vm_id}"

  _sprintf "head" "copy a virtual machine disks"

  _logger "head" \
    "${_FUNCTION_ID}()" \
    "copy a virtual machine disks"

  # shellcheck disable=SC2154
  _init_function "CheckRemoteStorage ${re_path}"

  # shellcheck disable=SC2154
  _init_function "XenVmCopy ${vm_id}"

  _sprintf "head" "extract ova files"

  _logger "head" \
    "${_FUNCTION_ID}()" \
    "extract ova files"

  # shellcheck disable=SC2154
  _init_function "XenVmExtract ${vm_id}"

  # shellcheck disable=SC2154
  _sprintf "head" "convert disks to '$pve_format' format"

  _logger "head" \
    "${_FUNCTION_ID}()" \
    "convert disks to '$pve_format' format"

  _x=1

  # shellcheck disable=SC2044
  _fname=""
  for _fname in $(find ./* -type d -name "Ref:*" | cut -d "/" -f2 | sort -V) ; do

    # shellcheck disable=SC2154
    _init_function "XenVmConvertDisks ${_fname}"

  done

  return $_STATE

}

# ``````````````````````````````````````````````````````````````````````````````
# Function name: XenVmCheck()
#
# Description:
#   Checks of the Xen remote virtual machine exist.
#
# Usage:
#   XenVmCheck vm_id
#
# Examples:
#   XenVmCheck PROD-web01
#

function XenVmCheck() {

  local _FUNCTION_ID="XenVmCheck"
  local _STATE=0

  local _vmid="$1"

  _msg_args+=(\
  "vm id: '${_vmid}'")

  _cmd_args+=(\
  "ssh ${ssh_opt} ${hv_host} -p ${port} if [[ ! \$(xe vm-list | grep ${_vmid}) ]] ; then exit 1 ; fi")

  return $_STATE

}

# ``````````````````````````````````````````````````````````````````````````````
# Function name: XenVmExport()
#
# Description:
#   Exports the Xen virtual machine:
#     - takes a virtual machine snapshot
#     - exports snapshot to file with extension 'ova'
#
# Usage:
#   XenVmExport vm_id
#
# Examples:
#   XenVmExport PROD-web01
#

function XenVmExport() {

  local _FUNCTION_ID="XenVmExport"
  local _STATE=0

  _cmdtime_state=1

  local _vmid="$1"

  _msg_args+=(\
  "creating snapshot: '${_vmid}-${_random}'" \
  "exporting snapshot: '${_vmid}.ova'")

  _cmd_args+=(\
  "ssh ${ssh_opt} ${hv_host} -p ${port} _id=\$(xe vm-snapshot vm=${_vmid} new-name-label=${_vmid}-${_random}) ; echo \$_id >>${_pv_xen_vars}" \
  "ssh ${ssh_opt} ${hv_host} -p ${port} _id=\$(cat ${_pv_xen_vars}) ; xe vm-export vm=\${_id} filename=${re_path}/${_vmid}.ova")

  return $_STATE

}

# ``````````````````````````````````````````````````````````````````````````````
# Function name: XenVmCopy()
#
# Description:
#   Copies the Xen virtual machine from remote host to local host.
#
# Usage:
#   XenVmCopy vm_id
#
# Examples:
#   XenVmCopy PROD-web01
#

function XenVmCopy() {

  local _FUNCTION_ID="XenVmCopy"
  local _STATE=0

  _cmdtime_state=1

  local _vmid="$1"

  _msg_args+=(\
  "checking: '${_vmid}.ova'" \
  "get src: '${_vmid}.ova'")

  _cmd_args+=(\
  "ssh ${ssh_opt} ${hv_host} -p ${port} if [[ ! -e \"${re_path}/${_vmid}.ova\" ]] ; then exit 1 ; fi" \
  "scp ${ssh_opt} -P ${port} ${hv_host}:${re_path}/${_vmid}.ova ${lo_path}")

  return $_STATE

}

# ``````````````````````````````````````````````````````````````````````````````
# Function name: XenVmExtract()
#
# Description:
#   Extracts the Xen virtual machine disks.
#
# Usage:
#   XenVmExtract vm_id
#
# Examples:
#   XenVmExtract PROD-web01
#

function XenVmExtract() {

  local _FUNCTION_ID="XenVmExtract"
  local _STATE=0

  _cmdtime_state=1

  local _vmid="$1"

  _msg_args+=(\
  "checking: '${_vmid}.ova'" \
  "src: '${_vmid}.ova'")

  _cmd_args+=(\
  "eval if [[ ! -e ${_vmid}.ova ]] ; then exit 1 ; fi" \
  "tar xf ${_vmid}.ova -C ${lo_path}")

  # shellcheck disable=SC2154
  if [[ "$remove_unused" == "yes" ]] ; then

    _msg_args+=(\
    "remove: '${_vmid}.ova'")

    _cmd_args+=(\
    "rm -fr ${_vmid}.ova")

  fi

  return $_STATE

}

# ``````````````````````````````````````````````````````````````````````````````
# Function name: XenVmConvertDisks()
#
# Description:
#   Converts the Xen virtual machine disks.
#
# Usage:
#   XenVmConvertDisks /path/to/local/xen/disk
#
# Examples:
#   XenVmConvertDisks /xfs900/datastore/xen/PROD-web01.{img,qcow2}
#

function XenVmConvertDisks() {

  local _FUNCTION_ID="XenVmConvertDisks"
  local _STATE=0

  # shellcheck disable=SC2034
  _cmdtime_state=1

  local _fdx="$1"

  local _fda
  local _fdb
  local _fdc

  # Store new directory/file name (eg. Ref_20).
  _fda=$(echo "$_fdx" | tr ":" "_")

  # Store new 'raw' file (eg. 1-Ref_20.img).
  _fdb="${_x}-${_fda}.img"

  _msg_args+=(\
  "checking: '${_fdx}'" \
  "src: '${_fdx}', dst: '${_fdb}'")

  _cmd_args+=(\
  "eval if [[ ! -d ${_fdx} ]] ; then exit 1 ; fi" \
  "xenmigrate --convert=${_fdx} ${_fdb}")

  if [[ "$remove_unused" == "yes" ]] ; then

    _msg_args+=(\
    "remove: '${_fdx}'")

    _cmd_args+=(\
    "rm -fr ${_fdx}")

  fi

  if [[ "$pve_format" == "qcow2" ]] ; then

    # Store 'qcow2' file name (eg. 1-Ref_20.qcow2).
    _fdc="${_fdb%.*}.qcow2"

    _msg_args+=(\
    "checking: '${_fdb}'" \
    "src: '${_fdb}', dst: '${_fdc}'")

    _cmd_args+=(\
    "eval if [[ ! -e ${_fdb} ]] ; then exit 1 ; fi" \
    "qemu-img convert -f raw -O qcow2 ${_fdb} ${_fdc}")

    if [[ "$remove_unused" == "yes" ]] ; then

      _msg_args+=(\
      "remove: '${_fdb}'")

      _cmd_args+=(\
      "rm -fr ${_fdb}")

    fi

  fi

  _x=$((_x + 1))

  return $_STATE

}
